Added map quads.txt
JSJitsu/ai-battle-engine pull request #23
Opened 2018-10-05 21:50 UTC by jakesmithdeveloper

2018-10-05 21:52 UTC, jakesmithdeveloper commented
Oops I lost the last column, let me fix that!

2018-10-06 00:33 UTC, Asuza requested changes

2018-10-06 00:33 UTC, Asuza commented on lib/maps/quads.txt
> +HW|IM|IM|IM|IM|IM|IM|IM|IM|iM|HW|IM
The game code isn't smart enough to gracefully handle any errors with the map, so `iM` will need to be fixed to `IM` before I can merge it. See https://github.com/JSJitsu/ai-battle-engine/blob/5a5e2406400135aa63c34f6065d883807539516c/index.js#L80 for the specific issue.

I created #25 if you're interested in working a related ticket.

2018-10-06 01:00 UTC, Asuza approved these changes
Thanks for the PR!

2018-10-06 01:00 UTC, merged